config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord

  validates :name, presence: true
  SPECIES = %w(dog cat snake rabbit turtle)
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pets_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @pet.update(pets_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def find_pet
    @pet = Pet.find(params[:id])
  end

  def pets_params
    params.require(:pet).permit(:name, :address, :found_on, :species)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets462</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on, as: :date, value: f.object.try(:strftime,"%m/%d/%Y") %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <%= render partial: "form", locals: { pet: @pet } %>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container">
  <h1>All the found pets</h1>
  <div class="row">
    <div class="col-6">
      <ol>
        <% @pets.each do |pet| %>
          <li class="mb-3">
            <%= link_to pet.name, pet_path(pet) %> -
            <%= link_to 'delete', pet_path(pet), method: :delete, class: 'btn btn-danger btn-xs' %>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
  <%= link_to 'Add a pet', new_pet_path, class: 'btn btn-primary' %>
</div>

app/views/pets/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <%= render partial: "form", locals: { pet: @pet } %>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-6">
      <h1><%= @pet.name %> - <%= @pet.species %></h1>

      <h2>Found at <%= @pet.address %> on <%= @pet.found_on.strftime('%A, %b %d') %></h2>

      <%= link_to 'Edit the pet', edit_pet_path(@pet), class: 'btn btn-warning' %>
    </div>
  </div>
</div>